version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: awestruckshoe/image-game-server
    container_name: image-node-server
    ports:
      - "8000:8000"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: awestruckshoe/image-game-client
    container_name: image-react-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge