services:
  simpxit:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - IMAGE_BUCKET=${IMAGE_BUCKET}
    ports: 
      - 3000:3000
    links:
      - redis
    depends_on:
      - redis
    
  redis:
    container_name: simpxit-redis
    image: redis/redis-stack-server:latest
    restart: unless-stopped

networks:
  default:
    name: simpxit-network
    driver: bridge
