/* eslint-disable react/no-unknown-property */
import { Canvas, type RenderCallback, useFrame } from '@react-three/fiber';
import { PointLight, Vector3, Group, Mesh } from 'three';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JoelHdez (https://sketchfab.com/JoelHdez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glazed-donut-simple-model-0bc473ee934f44c6bd124717cdf58c93
Title: Glazed donut_simple model
*/

import { OrbitControls, useGLTF } from '@react-three/drei';
import React, { Suspense, useRef } from 'react';


export function Donut({ animationCallback }: { animationCallback: (referenceGroup: React.RefObject<Group | null>) => RenderCallback }) {
  const { nodes, materials } = useGLTF('/gltf/donut/scene.gltf');
  const groupRef = useRef<Group>(null);

  useFrame(animationCallback(groupRef));

  return (
    <group ref={groupRef}>
      <group scale={2} position={[-0.006, -0.041, -0.006]} rotation={[2 * Math.PI / 3, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_2 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_3 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_4 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_5 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_6 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_7 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_8 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_9 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_10 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_11 as Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
    </group>
  );
}

export function DonutScene() {

  const cameraPosition = new Vector3(0, 0, 4);
  // Light positions are relative to camera
  const light1 = useRef<PointLight>(null);
  const light1Position = new Vector3(2, 2, 3);
  const light2 = useRef<PointLight>(null);
  const light2Position = new Vector3(-2, -1, 3);
  const light3 = useRef<PointLight>(null);
  const light3Position = new Vector3(0, 4, 5);

  function animationCallback(donutRef: React.RefObject<Group | null>): RenderCallback {
    return (_, delta) => {
      if (donutRef.current) {
        donutRef.current.rotateY(- 1 * delta / 3);
        donutRef.current.rotateZ(-1 * delta / 4);
      }
    };
  }

  return (
    <div className="z-10 flex-fill w-100 my-lg-3 mb-lg-5">
      <Canvas
        camera={{
          position: cameraPosition,
          fov: 75,
          near: 0.1,
          far: 1000,
        }}
      >
        <Suspense fallback={<></>}>
          <ambientLight color={"white"} intensity={.5} />
          <pointLight intensity={10} color={"pink"} ref={light1} position={cameraPosition.clone().add(light1Position)} />
          <pointLight intensity={15} color={"pink"} ref={light2} position={cameraPosition.clone().add(light2Position)} />
          <pointLight intensity={7} ref={light3} position={cameraPosition.clone().add(light3Position)} />
          <Donut animationCallback={animationCallback} />
          <OrbitControls enablePan={false} enableZoom={false}
            onChange={(e) => {
              if (!e || !e.target) return;
              const camera = e.target.object;
              const newPosition = camera.position;
              if (light1.current) {
                light1.current.position.copy(newPosition.clone().add(light1Position));
              }
              if (light2.current) {
                light2.current.position.copy(newPosition.clone().add(light2Position));
              }
              if (light3.current) {
                light3.current.position.copy(newPosition.clone().add(light3Position));
              }

            }} />
        </Suspense>
      </Canvas>
    </div>
  );
}