/* eslint-disable react/no-unknown-property */
import { Canvas, type RenderCallback, useFrame } from '@react-three/fiber';
import * as THREE from 'three';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JoelHdez (https://sketchfab.com/JoelHdez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glazed-donut-simple-model-0bc473ee934f44c6bd124717cdf58c93
Title: Glazed donut_simple model
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

useGLTF.preload('/glft/donut/scene.gltf');

export function Donut({ animationCallback }: { animationCallback: (referenceGroup: React.RefObject<THREE.Group | null>) => RenderCallback }) {
  const { nodes, materials } = useGLTF('/gltf/donut/scene.gltf');
  const groupRef = useRef<THREE.Group>(null);

  useFrame(animationCallback(groupRef));

  return (
    <group ref={groupRef}>
      <group scale={2} position={[0, 0, 0.1]} rotation={[Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_2 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_3 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_4 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_5 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_6 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_7 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_8 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_9 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_10 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_11 as THREE.Mesh).geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
    </group>
  );
}

export function DonutScene() {

  function animationCallback(donutRef: React.RefObject<THREE.Group | null>): RenderCallback {
    return (_, delta) => {
      if (donutRef.current) {
        donutRef.current.rotateY(delta);
      }
    };
  }

  return (
    <div className="fixed top-0 left-0 w-full h-full -z-10">
      <Canvas
        camera={{
          position: [0, 0, 5],
          fov: 75,
          near: 0.1,
          far: 1000,
        }}
      >
        <ambientLight intensity={0.9} />
        <Donut animationCallback={animationCallback} />
      </Canvas>
    </div>
  );
}